"""
Action Card UI Components — OI-69
====================================

Streamlit rendering components for action cards generated by the
:class:`~omniview.rules.action_cards.ActionCardGenerator`.

These components are consumed by ``app.py`` to display action cards
in the live dashboard, giving plant managers and maintenance engineers
reviewable, human-readable recommendations with physical rationale.

Usage in app.py::

    from omniview.dashboard.action_card_ui import render_action_cards_section
    render_action_cards_section(hours=24)
"""

from __future__ import annotations

import logging
from typing import Any

import streamlit as st

from omniview.rules.action_cards import ActionCard

logger = logging.getLogger(__name__)

# ── Severity styling ────────────────────────────────────────────────────

_SEVERITY_STYLES: dict[str, dict[str, str]] = {
    "CRITICAL": {
        "bg": "#3d0000",
        "border": "#e74c3c",
        "badge_bg": "#e74c3c",
        "badge_text": "white",
        "icon": "🔴",
    },
    "WARNING": {
        "bg": "#3d2e00",
        "border": "#f39c12",
        "badge_bg": "#f39c12",
        "badge_text": "white",
        "icon": "🟡",
    },
    "INFO": {
        "bg": "#002a3d",
        "border": "#3498db",
        "badge_bg": "#3498db",
        "badge_text": "white",
        "icon": "🔵",
    },
}


# ── Card CSS ────────────────────────────────────────────────────────────

_CARD_CSS = """
<style>
    .action-card {
        border-radius: 12px;
        padding: 20px;
        margin-bottom: 16px;
        box-shadow: 0 4px 15px rgba(0, 0, 0, 0.4);
    }
    .action-card-title {
        font-size: 1.15rem;
        font-weight: 700;
        color: #e6f1ff;
        margin-bottom: 8px;
    }
    .action-card-summary {
        color: #a8b2d1;
        font-size: 0.9rem;
        line-height: 1.5;
        margin-bottom: 12px;
    }
    .action-box {
        border-radius: 8px;
        padding: 12px 16px;
        margin-bottom: 8px;
    }
    .action-box-do {
        background: rgba(46, 204, 113, 0.15);
        border-left: 4px solid #2ecc71;
    }
    .action-box-donot {
        background: rgba(231, 76, 60, 0.15);
        border-left: 4px solid #e74c3c;
    }
    .action-box-label {
        font-size: 0.75rem;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        margin-bottom: 4px;
    }
    .action-box-do .action-box-label {
        color: #2ecc71;
    }
    .action-box-donot .action-box-label {
        color: #e74c3c;
    }
    .action-box-text {
        color: #ccd6f6;
        font-size: 0.85rem;
        line-height: 1.4;
    }
    .rupee-badge {
        display: inline-block;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 0.8rem;
        font-weight: 600;
        margin-right: 8px;
        margin-bottom: 8px;
    }
    .urgency-badge {
        display: inline-block;
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 0.8rem;
        font-weight: 600;
        background: rgba(155, 89, 182, 0.2);
        color: #bb86fc;
        border: 1px solid #9b59b6;
    }
    .severity-badge {
        display: inline-block;
        padding: 2px 10px;
        border-radius: 12px;
        font-size: 0.7rem;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 0.05em;
        margin-right: 8px;
    }
    .target-role {
        color: #8892b0;
        font-size: 0.75rem;
        margin-top: 4px;
    }
</style>
"""

_CSS_INJECTED = False


def _inject_css() -> None:
    """Inject action card CSS once per session."""
    global _CSS_INJECTED  # noqa: PLW0603
    if not _CSS_INJECTED:
        st.markdown(_CARD_CSS, unsafe_allow_html=True)
        _CSS_INJECTED = True


# ── Role display names ──────────────────────────────────────────────────

_ROLE_DISPLAY: dict[str, str] = {
    "plant_manager": "👔 Plant Manager",
    "maintenance_engineer": "🔧 Maintenance Engineer",
    "operator": "👷 Floor Operator",
    "finance": "📊 Finance / ESG",
}


# ── Render a single action card ─────────────────────────────────────────


def render_action_card(card: ActionCard) -> None:
    """Render a single action card as a styled Streamlit component.

    Parameters
    ----------
    card : ActionCard
        The action card to render.
    """
    _inject_css()

    style = _SEVERITY_STYLES.get(card.severity, _SEVERITY_STYLES["INFO"])

    # ── Card container ──────────────────────────────────────────────────
    st.markdown(
        f"""
        <div class="action-card" style="
            background: {style['bg']};
            border: 1px solid {style['border']};
        ">
            <div style="display: flex; align-items: center; margin-bottom: 8px;">
                <span class="severity-badge" style="
                    background: {style['badge_bg']};
                    color: {style['badge_text']};
                ">{card.severity}</span>
                <span style="color: #8892b0; font-size: 0.75rem;">
                    {card.device_id} · {card.timestamp.strftime('%H:%M') if hasattr(card.timestamp, 'strftime') else card.timestamp}
                </span>
            </div>
            <div class="action-card-title">{card.title}</div>
            <div class="action-card-summary">{card.summary}</div>
        """,
        unsafe_allow_html=True,
    )

    # ── Badges ──────────────────────────────────────────────────────────
    badges_html = ""
    if card.rupee_impact:
        badges_html += (
            f'<span class="rupee-badge" style="'
            f"background: rgba(241, 196, 15, 0.2); "
            f"color: #f1c40f; "
            f"border: 1px solid #f39c12;"
            f'">💰 {card.rupee_impact}</span>'
        )
    if card.urgency_window:
        badges_html += f'<span class="urgency-badge">⏱️ {card.urgency_window}</span>'

    if badges_html:
        st.markdown(badges_html, unsafe_allow_html=True)

    # ── Action boxes ────────────────────────────────────────────────────
    st.markdown(
        f"""
            <div class="action-box action-box-do">
                <div class="action-box-label">✅ Recommended Action</div>
                <div class="action-box-text">{card.recommended_action}</div>
            </div>
        """,
        unsafe_allow_html=True,
    )

    if card.do_not:
        st.markdown(
            f"""
                <div class="action-box action-box-donot">
                    <div class="action-box-label">🚫 Do NOT</div>
                    <div class="action-box-text">{card.do_not}</div>
                </div>
            """,
            unsafe_allow_html=True,
        )

    # ── Target role ─────────────────────────────────────────────────────
    role_display = _ROLE_DISPLAY.get(card.target_role, card.target_role)
    st.markdown(
        f'<div class="target-role">Route to: {role_display}</div>',
        unsafe_allow_html=True,
    )

    # ── Close card container ────────────────────────────────────────────
    st.markdown("</div>", unsafe_allow_html=True)

    # ── Expandable sections (for internal review) ───────────────────────
    with st.expander("🔬 Physical Rationale (internal review)"):
        st.markdown(card.physical_rationale or "_No rationale provided._")

    with st.expander("📊 Source Sensor Readings"):
        if card.sensor_readings:
            for k, v in card.sensor_readings.items():
                st.text(f"  {k}: {v}")
        else:
            st.text("  No sensor readings attached.")


# ── Section renderer ────────────────────────────────────────────────────


def render_action_cards_section(cards: list[ActionCard]) -> None:
    """Render the full action cards section in the dashboard.

    Parameters
    ----------
    cards : list[ActionCard]
        Action cards to display, typically from ``get_action_cards()``.
    """
    _inject_css()

    st.markdown(
        '<p class="section-header">🎯 Action Cards</p>',
        unsafe_allow_html=True,
    )

    if not cards:
        st.info(
            "No action cards generated. Cards appear when rule/PdM events "
            "or scenario-labeled readings are detected."
        )
        return

    # Summary counts
    critical = sum(1 for c in cards if c.severity == "CRITICAL")
    warning = sum(1 for c in cards if c.severity == "WARNING")
    info_ = sum(1 for c in cards if c.severity == "INFO")

    scol1, scol2, scol3, scol4 = st.columns(4)
    with scol1:
        st.metric("Total Cards", len(cards))
    with scol2:
        st.metric("🔴 Critical", critical)
    with scol3:
        st.metric("🟡 Warning", warning)
    with scol4:
        st.metric("🔵 Info", info_)

    st.markdown("---")

    # Render cards — critical first
    sorted_cards = sorted(
        cards,
        key=lambda c: {"CRITICAL": 0, "WARNING": 1, "INFO": 2}.get(c.severity, 3),
    )

    for card in sorted_cards:
        render_action_card(card)
